
services:

  mongodb:
    image: mongo:8.0.29
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?required}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?required}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ping: 1})'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  postgresdb:
    image: postgres:18.6
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
      POSTGRES_DB: ${POSTGRES_DB:?required}
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  web_interface:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver_ui
    restart: unless-stopped
    ports:
      - "8080:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      mongodb:
        condition: service_healthy
      postgresdb:
        condition: service_healthy


volumes:
  mongodb-data:
    driver: local
  postgres-data:
    driver: local
  cloudbeaver-data:
    driver: local


